# Generated by Django 5.1.15 on 2026-04-30 02:28

import apps.bonsai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonsaiMedia",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.bonsai.models.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_original",
                    models.ImageField(
                        help_text="長辺 2048px を超える場合はサーバ側でリサイズして保存",
                        upload_to="bonsai/original/%Y/%m/",
                        verbose_name="元画像",
                    ),
                ),
                (
                    "image_medium",
                    models.ImageField(
                        blank=True,
                        upload_to="bonsai/medium/%Y/%m/",
                        verbose_name="中サイズ画像",
                    ),
                ),
                (
                    "image_thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="bonsai/thumb/%Y/%m/",
                        verbose_name="サムネイル画像",
                    ),
                ),
                (
                    "taken_at",
                    models.DateField(blank=True, null=True, verbose_name="撮影日"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="キャプション"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "盆栽画像",
                "verbose_name_plural": "盆栽画像",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BonsaiPlant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.bonsai.models.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ユーザーが付ける名前（例: 太郎）",
                        max_length=80,
                        verbose_name="個体名",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateField(blank=True, null=True, verbose_name="入手日"),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("good", "良好"),
                            ("watch", "要注意"),
                            ("poor", "不調"),
                        ],
                        default="good",
                        max_length=16,
                        verbose_name="健康状態",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "cover_media",
                    models.ForeignKey(
                        blank=True,
                        help_text="一覧などで表示する代表画像",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_for",
                        to="bonsai.bonsaimedia",
                        verbose_name="代表画像",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonsai_plants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "盆栽",
                "verbose_name_plural": "盆栽",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bonsaimedia",
            name="bonsai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="bonsai.bonsaiplant",
                verbose_name="盆栽",
            ),
        ),
        migrations.CreateModel(
            name="BonsaiSpecies",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.bonsai.models.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL に利用する一意な識別子（例: kuromatsu）",
                        max_length=64,
                        unique=True,
                        verbose_name="URL スラッグ",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="和名（例: 黒松）",
                        max_length=80,
                        verbose_name="品種名",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=120, verbose_name="学名"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conifer", "針葉樹"),
                            ("broadleaf", "広葉樹"),
                            ("flowering", "花物"),
                            ("fruiting", "実物"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="品種の特徴や育成のコツ",
                        verbose_name="解説",
                    ),
                ),
                (
                    "monthly_tasks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="月別の標準作業を JSON 配列で保持する。例: [{month: 5, period: '上旬', task_type: 'bud_pinching', description: '...'}]",
                        verbose_name="月別作業カレンダー",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="species/cover/%Y/%m/",
                        verbose_name="代表画像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "品種",
                "verbose_name_plural": "品種",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="bonsai_bons_categor_eb9712_idx"
                    ),
                    models.Index(fields=["slug"], name="bonsai_bons_slug_fe2334_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="bonsaiplant",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="マスタにない品種は空欄でも登録可能",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plants",
                to="bonsai.bonsaispecies",
                verbose_name="品種",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.bonsai.models.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="タグ名")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex カラー（例: #4CAF50）",
                        max_length=16,
                        verbose_name="カラー",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonsai_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "タグ",
                "verbose_name_plural": "タグ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BonsaiTag",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.bonsai.models.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "bonsai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="bonsai.bonsaiplant",
                        verbose_name="盆栽",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonsai_links",
                        to="bonsai.tag",
                        verbose_name="タグ",
                    ),
                ),
            ],
            options={
                "verbose_name": "盆栽タグ",
                "verbose_name_plural": "盆栽タグ",
            },
        ),
        migrations.AddField(
            model_name="bonsaiplant",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="bonsai_plants",
                through="bonsai.BonsaiTag",
                to="bonsai.tag",
                verbose_name="タグ",
            ),
        ),
        migrations.AddIndex(
            model_name="bonsaimedia",
            index=models.Index(
                fields=["bonsai", "-created_at"], name="bonsai_bons_bonsai__204438_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_tag_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="bonsaitag",
            constraint=models.UniqueConstraint(
                fields=("bonsai", "tag"), name="uniq_bonsaitag_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="bonsaiplant",
            index=models.Index(
                fields=["user", "-created_at"], name="bonsai_bons_user_id_489b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bonsaiplant",
            index=models.Index(
                fields=["health_status"], name="bonsai_bons_health__7a0067_idx"
            ),
        ),
    ]
