# Generated by Django 5.1.15 on 2026-04-30 02:32

import apps.common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonsai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSpeciesRelation',
            fields=[
                ('id', models.CharField(default=apps.common.utils.uuid7_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('relevance', models.PositiveSmallIntegerField(default=0, verbose_name='関連度スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_relations', to='bonsai.bonsaispecies', verbose_name='品種')),
            ],
            options={
                'verbose_name': '記事-品種関連',
                'verbose_name_plural': '記事-品種関連',
                'ordering': ('-relevance', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.CharField(default=apps.common.utils.uuid7_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='スラッグ')),
                ('body', models.TextField(verbose_name='本文（Markdown）')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='概要')),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/cover/%Y/%m/', verbose_name='カバー画像')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開')], default='draft', max_length=16, verbose_name='公開ステータス')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='執筆者')),
                ('related_species', models.ManyToManyField(blank=True, related_name='articles', through='articles.ArticleSpeciesRelation', to='bonsai.bonsaispecies', verbose_name='関連品種')),
            ],
            options={
                'verbose_name': 'お役立ち記事',
                'verbose_name_plural': 'お役立ち記事',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='articlespeciesrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_relations', to='articles.helparticle', verbose_name='お役立ち記事'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['status'], name='article_status_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['slug'], name='article_slug_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlespeciesrelation',
            unique_together={('article', 'species')},
        ),
    ]
