# Generated by Django 5.1.15 on 2026-09-08 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("bonsai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helparticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("tips", "作業TIPS"),
                    ("species_guide", "品種ガイド"),
                    ("pest", "病害虫対策"),
                    ("gallery", "ギャラリー"),
                    ("other", "その他"),
                ],
                default="tips",
                max_length=24,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="お役立ちトップの特集バナーに表示する",
                verbose_name="特集",
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(fields=["category"], name="article_category_idx"),
        ),
    ]
