# Generated by Django 5.1.15 on 2026-04-30 05:11

import apps.common.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bonsai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fertilizer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.common.utils.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="肥料名")),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("solid", "固形"),
                            ("liquid", "液体"),
                            ("other", "その他"),
                        ],
                        default="solid",
                        max_length=16,
                        verbose_name="形状",
                    ),
                ),
                (
                    "n",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="窒素 (N) %",
                    ),
                ),
                (
                    "p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="リン酸 (P) %",
                    ),
                ),
                (
                    "k",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="カリウム (K) %",
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(default=False, verbose_name="有機肥料"),
                ),
                ("note", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL の場合は共通マスタ（管理者編集）",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "肥料",
                "verbose_name_plural": "肥料",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CareLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.common.utils.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("watering", "潅水"),
                            ("fertilizing", "施肥"),
                            ("pruning", "剪定"),
                            ("repotting", "植え替え"),
                            ("observation", "観察"),
                            ("bud_pinching", "芽摘み"),
                            ("defoliation", "葉刈り"),
                            ("leaf_misting", "葉水"),
                            ("wiring", "針金かけ"),
                            ("unwiring", "針金外し"),
                            ("pest_control", "消毒"),
                            ("jin_shari", "ジン・シャリ作り"),
                            ("air_layering", "取り木"),
                            ("cutting", "挿し木"),
                            ("other", "その他"),
                        ],
                        default="observation",
                        max_length=32,
                        verbose_name="作業種別",
                    ),
                ),
                (
                    "task_type_other",
                    models.CharField(
                        blank=True,
                        help_text="task_type が「その他」のときの自由入力",
                        max_length=80,
                        verbose_name="作業種別（その他）",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="実施日時"
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "晴れ"),
                            ("cloudy", "曇り"),
                            ("rainy", "雨"),
                            ("snowy", "雪"),
                            ("other", "その他"),
                        ],
                        max_length=16,
                        verbose_name="天候",
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="気温 (℃)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="care_logs/%Y/%m/", verbose_name="写真"
                    ),
                ),
                (
                    "fertilizer_amount",
                    models.CharField(
                        blank=True,
                        help_text="自由入力（例: 1g、3粒）",
                        max_length=40,
                        verbose_name="肥料の量",
                    ),
                ),
                (
                    "health_evaluation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1: 非常に悪い"),
                            (2, "2: 悪い"),
                            (3, "3: 普通"),
                            (4, "4: 良い"),
                            (5, "5: 非常に良い"),
                        ],
                        help_text="1〜5 の 5 段階評価",
                        null=True,
                        verbose_name="状態評価",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "bonsai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bonsai.bonsaiplant",
                        verbose_name="盆栽",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="通常は bonsai.user と同じ値（権限チェック簡略化のため冗長保持）",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実施ユーザー",
                    ),
                ),
                (
                    "fertilizer",
                    models.ForeignKey(
                        blank=True,
                        help_text="施肥時のみ指定する",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="logs.fertilizer",
                        verbose_name="使用した肥料",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業ログ",
                "verbose_name_plural": "作業ログ",
                "ordering": ("-performed_at",),
            },
        ),
        migrations.AddIndex(
            model_name="fertilizer",
            index=models.Index(
                fields=["user", "name"], name="logs_fertil_user_id_f1a632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["bonsai", "-performed_at"],
                name="logs_carelo_bonsai__3513ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["task_type"], name="logs_carelo_task_ty_167360_idx"
            ),
        ),
    ]
