# Generated by Django 5.1.15 on 2026-04-30 05:11

import apps.common.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bonsai", "0001_initial"),
        ("logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyAdvice",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.common.utils.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="対象月",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="タイトル")),
                ("advice_text", models.TextField(verbose_name="アドバイス本文")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="例: 灌水、全般、病害虫など任意のラベル",
                        max_length=32,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "月次アドバイス",
                "verbose_name_plural": "月次アドバイス",
                "ordering": ("month", "title"),
                "indexes": [
                    models.Index(fields=["month"], name="schedules_m_month_7470a8_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CareSchedule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.common.utils.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("watering", "潅水"),
                            ("fertilizing", "施肥"),
                            ("pruning", "剪定"),
                            ("repotting", "植え替え"),
                            ("observation", "観察"),
                            ("bud_pinching", "芽摘み"),
                            ("defoliation", "葉刈り"),
                            ("leaf_misting", "葉水"),
                            ("wiring", "針金かけ"),
                            ("unwiring", "針金外し"),
                            ("pest_control", "消毒"),
                            ("jin_shari", "ジン・シャリ作り"),
                            ("air_layering", "取り木"),
                            ("cutting", "挿し木"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="作業種別",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="例: 黒松の水やり",
                        max_length=120,
                        verbose_name="タスク名",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("none", "繰り返しなし"),
                            ("daily", "毎日"),
                            ("weekly", "毎週"),
                            ("monthly", "毎月"),
                            ("yearly", "毎年"),
                            ("custom", "カスタム"),
                        ],
                        default="none",
                        max_length=16,
                        verbose_name="繰り返し種別",
                    ),
                ),
                (
                    "repeat_rule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='iCal RFC5545 風の JSON。例: {"interval": 7, "byweekday": ["MO"]}',
                        verbose_name="繰り返しルール",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                (
                    "next_run_at",
                    models.DateField(
                        blank=True,
                        help_text="一覧クエリ高速化のため都度キャッシュする",
                        null=True,
                        verbose_name="次回予定日",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "bonsai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bonsai.bonsaiplant",
                        verbose_name="対象盆栽",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="権限チェック簡略化のため非正規化して保持する",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "ケアスケジュール",
                "verbose_name_plural": "ケアスケジュール",
                "ordering": ["next_run_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "next_run_at"],
                        name="schedules_c_user_id_079646_idx",
                    ),
                    models.Index(
                        fields=["bonsai", "is_active"],
                        name="schedules_c_bonsai__bfb277_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CareScheduleCompletion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.common.utils.uuid7_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("species_task", "品種マスタ由来"),
                            ("schedule", "ユーザー個別スケジュール"),
                            ("advice", "月次共通アドバイス"),
                        ],
                        max_length=16,
                        verbose_name="参照元種別",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="例: species_task:{species_id}:{month}:{task_index} / schedule:{schedule_id} / advice:{advice_id}",
                        max_length=200,
                        verbose_name="参照キー",
                    ),
                ),
                (
                    "year_month",
                    models.DateField(
                        help_text="対象月の 1 日固定（年月単位の完了状態）",
                        verbose_name="対象年月",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "完了"),
                            ("skipped", "スキップ"),
                            ("pending", "保留"),
                        ],
                        default="done",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="完了日時"
                    ),
                ),
                (
                    "bonsai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="bonsai.bonsaiplant",
                        verbose_name="対象盆栽",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        blank=True,
                        help_text="プリフィル経由で作成したログへの参照",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to="logs.carelog",
                        verbose_name="関連ケアログ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ToDo 完了状態",
                "verbose_name_plural": "ToDo 完了状態",
                "ordering": ("-completed_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "year_month"],
                        name="schedules_c_user_id_6e4987_idx",
                    ),
                    models.Index(
                        fields=["bonsai", "year_month"],
                        name="schedules_c_bonsai__ac842b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source_type", "source_ref", "year_month"),
                        name="unique_completion_per_month",
                    )
                ],
            },
        ),
    ]
